apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssff
  template:
    metadata:
      labels:
        app: ssff
    spec:
      containers:
      - image: okteto.dev/ssff:latest
        name: ssff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6449e11e-5f4f-436b-bf88-6eb27518fa3a"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "6449e11e-5f4f-436b-bf88-6eb27518fa3a"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
